{% set name = "xarray_leaflet" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c02c85e9459e27f392909d37b6a82b4c2d2df04e68690046cfd03aace6bfe99

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.0
    - pip
  run:
    - python
    - xarray
    - jupyter_server
    - ipyleaflet
    - pillow
    - rasterio
    - affine
    - mercantile

test:
  imports:
    - xarray_leaflet
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/davidbrochart/xarray-leaflet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An xarray extension for tiled map plotting.
  description: |
    xarray-leaflet uses ipyleaflet as a plotting backend for data arrays. It generates map tiles
    on the fly, possibly using Dask's lazy evaluation system and Zarr's chunked data storage, and
    serves them through the Jupyter server, allowing for big data visualization.
  dev_url: https://github.com/davidbrochart/xarray-leaflet

extra:
  recipe-maintainers:
    - davidbrochart
