{% set name = "xarray_leaflet" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 569894912037b034cc801f644f9f39f0d60e3f1753e946d907a7e33f3876d6ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.0
    - pip
  run:
    - python
    - rioxarray >=0.0.30
    - jupyter_server >=0.3.0
    - ipyleaflet >=0.13.1
    - pillow >=7
    - matplotlib-base >=3
    - affine >=2
    - mercantile >=1

test:
  imports:
    - xarray_leaflet
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/davidbrochart/xarray-leaflet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An xarray extension for tiled map plotting.
  description: |
    xarray-leaflet uses ipyleaflet as a plotting backend for data arrays. It generates map tiles
    on the fly, possibly using Dask's lazy evaluation system and Zarr's chunked data storage, and
    serves them through the Jupyter server, allowing for big data visualization.
  dev_url: https://github.com/davidbrochart/xarray-leaflet

extra:
  recipe-maintainers:
    - davidbrochart
