{% set name = "xarray_leaflet" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d418c243166e0967ea34623b9253143c7e124e70fea2b87210333d7d0a7ee8d0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.0
    - pip
  run:
    - python
    - xarray
    - jupyter_server
    - ipyleaflet >=0.13.0
    - pillow
    - matplotlib-base
    - rasterio
    - affine
    - mercantile

test:
  imports:
    - xarray_leaflet
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/davidbrochart/xarray-leaflet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An xarray extension for tiled map plotting.
  description: |
    xarray-leaflet uses ipyleaflet as a plotting backend for data arrays. It generates map tiles
    on the fly, possibly using Dask's lazy evaluation system and Zarr's chunked data storage, and
    serves them through the Jupyter server, allowing for big data visualization.
  dev_url: https://github.com/davidbrochart/xarray-leaflet

extra:
  recipe-maintainers:
    - davidbrochart
